concourse/concourse-chart

Chart.yaml, templates/web-deployment.yaml, values.yaml
Adds these flags:
```
CONCOURSE_NEWRELIC_BATCH_DURATION
CONCOURSE_NEWRELIC_BATCH_SIZE
CONCOURSE_NEWRELIC_BATCH_DISABLE_COMPRESSION
```
From https://github.com/concourse/concourse/pull/4698
=> Add NewRelic batch flags

Chart.yaml, README.md, templates/web-deployment.yaml, values.yaml
Adding `orgGuid` and updating the existing org/space flags.
=> update the main team cf params

CHANGELOG.md
Made some typo and stylistic changes as well.
=> Update CHANGELOG.md for 9.0.0

Chart.yaml, README.md, templates/web-deployment.yaml, values.yaml
This reverts commit f396a01c3f5b6a876ad99efc452066b31ddb8aa2.
=> Revert "update the main team cf params"

.github/pull_request_template.md
=> Add checkbox item to remind maintainer to backport if needed

Chart.yaml
Officially adding myself to the list 😬
=> Update maintainers list

CHANGELOG.md, Chart.yaml, templates/web-deployment.yaml, templates/worker-statefulset.yaml, values.yaml
With the 6.0 release, some flags were added, other removed.
https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-check-helm-params/builds/65
This PR makes sure we get that right :grin: 
- remove `noop`
- add `job-scheduling-max-in-flight`
- split maxconns in api and backend
- remove enableLidar
- add `useContainerd`
- ~[ ] Variables are documented in the `README.md`~ the vars are all concourse specific
=> Update configuration for 6.0 release

Chart.yaml, templates/web-deployment.yaml, values.yaml
Signed-off-by: TJ Higgins <tj@architect.io>
blocked by: https://github.com/concourse/concourse/pull/5432
=> Fix typo with componentRunnerInterval

Chart.yaml, templates/web-deployment.yaml, templates/web-secrets.yaml, templates/worker-statefulset.yaml, values.yaml
=> 6.1 - add missing params

Chart.yaml, templates/web-deployment.yaml, values.yaml
This configuration allows Insights url to be configured for EU or US data centres.
Refer corresponding [Pull request in Concourse](https://github.com/concourse/concourse/pull/5532)
*  Add `newrelic.url` in values.yml
*  Add corresponding value to `templates/web-deployment.yaml`
*  Bump chart version
**NewRelic values are not documented in README.md**
=> Add configuration for NewRelic Insights URL

templates/web-deployment.yaml, values.yaml
This feature was added to the web command in concourse/concourse#5192. Adding flag to Helm chart for parity.
=> Make CONCOURSE_ENABLE_RERUN_WHEN_WORKER_DISAPPEARS configurable

README.md
Fixes simple README issues.
> What are the changes included in this PR? Feel free to add as many lines as needed below.
* Changes 5.8.0 to 6.1.0 to match values.
=> Update README for 6.1

Chart.yaml, templates/web-deployment.yaml, values.yaml
for https://github.com/concourse/concourse/pull/5013
=> add config for vault lookup paths

templates/web-deployment.yaml, values.yaml
=> add max checks per second configuration to chart

templates/web-deployment.yaml, values.yaml
adds properties for OPA (https://github.com/concourse/concourse/pull/5034)
=> add properties for OPA and policy checking

templates/web-deployment.yaml, values.yaml
> Please remove all the lines starting with '>'
> Hi there! Thanks for submitting a pull request to the Concourse Helm chart!
> If you haven't already, please take a look at our [Code of Conduct](https://github.com/concourse/concourse/blob/master/CODE_OF_CONDUCT.md).
> To help us review your PR, please fill in the following information.
> Feel free to delete any sections not applicable to your pull request.
> No issue number? Please give us a few lines of context describing the need for this PR.
Adds a feature flag for the newly added across step - https://github.com/concourse/concourse/pull/5887
> What are the changes included in this PR? Feel free to add as many lines as needed below.
* 
* 
*
> Are the following items included as part of this PR? Please delete checkbox items that don't …
=> add feature flag for across step

README.md, templates/web-deployment.yaml, templates/web-secrets.yaml, values.yaml
Needed after concourse/concourse#5998 was merged
* Add the flags required for SAML auth
=> Add SAML auth configuration

values.yaml
Wasn't clear what kind of release we're talking about
=> Be specific about what “release” means here

README.md, templates/_helpers.tpl, values.yaml
Part of concourse/concourse#5985
In order to reason about the configurable parameters of Concourse binary and the distributions more easily we should expose options in the binary in both the Helm chart and BOSH release to the greatest degree possible. See https://github.com/concourse/concourse/issues/5985#issuecomment-692202317
* Add maxContainers and networkPool to worker.garden
> fill out …
=> Add guardian flags

templates/_helpers.tpl, values.yaml
This flag was added in concourse/concourse#6086.
Signed-off-by: Muntasir Chowdhury <mchowdhury@pivotal.io>
part of concourse/concourse#6086
=> add CONCOURSE_CONTAINERD_INIT_BIN

templates/web-deployment.yaml, values.yaml
Option removed in concourse/concourse#6022
=> remove lidar checker interval

templates/_helpers.tpl, values.yaml
Part of concourse/concourse#6120
=> add CONCOURSE_CONTAINERD_CNI_PLUGINS_DIR

templates/web-configmap.yaml, templates/web-deployment.yaml, values.yaml
Don't merge till https://github.com/concourse/concourse/pull/6079 is in
=> allow configuring defaults for base resource types

templates/web-deployment.yaml, values.yaml
=> add feature flag for instanced pipelines

templates/web-deployment.yaml, values.yaml
=> Add honeycomb.io tracing env vars

templates/web-deployment.yaml, values.yaml
Because we've recently added some helpful extra config for tracing that should be exposed in the helm chart!
* attributes and headers are maps, I think it's a nicer way to specify rather than requiring a comma-separated list of colon-separated pairs
=> add new tracing configs

templates/web-deployment.yaml, values.yaml
=> add build events bigint migration config

templates/web-configmap.yaml, templates/web-deployment.yaml, values.yaml
We cherry picked the resource defaults commit from dev, hopefully that won't cause any issues when it tries auto-merge master into dev
=> Merge release/6.7.x

README.md, templates/web-secrets.yaml, templates/worker-secrets.yaml, values.yaml
Fixes #170
* Add annotations capabilities for the web and worker secrets.
=> Allow secrets annotations

templates/web-deployment.yaml, values.yaml
Concourse part PR is https://github.com/concourse/concourse/pull/6271
=> Add a new flag enable-skip-checking-not-in-use-resources.

templates/web-deployment.yaml, values.yaml
syncs values.yml + templates to latest flags on Concourse `master`
* remove bigint migration flags
* add flags for placement strategy changes
- i would like to peacefully protest this as it doesn't even include the properties we changed and should really just be generated by a script or something
=> remove bigint migration flags, add placement strategy flags

templates/web-deployment.yaml, values.yaml
New flags added in concourse/concourse#6413
~Note: the flags were also added to concourse master in concourse/concourse#6362 - I'm just making a PR to concourse-chart master though, since that'll make it's way into dev~
=> Add vault timeout flags + var_source GC interval

templates/web-deployment.yaml
=> add postgres key mounts to init container

README.md, templates/web-deployment.yaml, templates/web-secrets.yaml, values.yaml
added in concourse/concourse#6355
=> Add tls CA cert flag

templates/web-deployment.yaml, templates/web-secrets.yaml
=> Make web TLS CA cert optional

templates/_helpers.tpl, values.yaml
Follow up to concourse/concourse#6624
=> add params for MTU + external IP

CHANGELOG.md
=> Adds release note for major version bump to 15.0.0

templates/web-deployment.yaml, values.yaml
no
The values.yml contains a duplicate key which can irritate parsers as well as human readers.
Remove the duplicate key in values.yml
- unchanged: no additional variable, none removed
- `master`
=> Remove duplicate key in values.yml

OWNERS
This was back when the repo was part of the helm chart repo. Not needed anymore.
=> Remove owners

templates/web-api-svc.yaml, templates/web-prometheus-svc.yaml, values.yaml
Backports:
- concourse/concourse-chart#227
- concourse/concourse-chart#228
fixes concourse/concourse#6774
=> Backport chart fixes to 6.7.x

templates/web-deployment.yaml, values.yaml
=> [release/7.2.x] add ldap password connector flags

templates/web-deployment.yaml, values.yaml
same as #240, but for dev branch
* 
* 
*
=> [dev] add ldap password connector flags

templates/web-deployment.yaml
=> [release/7.2.x] fix ldap username prompt dev

templates/web-deployment.yaml
=> [dev] fix password connector env var

templates/web-deployment.yaml, values.yaml
Add the CSP flag from concourse/concourse#6949
=> Add ContentSecuritPolicy flag

templates/web-deployment.yaml, values.yaml
Related to concourse/concourse#7049
* 
* 
*
=> Disable caching streamed volumes by default

templates/web-deployment.yaml, values.yaml
https://github.com/concourse/concourse/pull/7125
=> add properties for resource causality

templates/web-deployment.yaml, values.yaml
and refactor the setting of AGENT_HOST/AGENT_PATH - now, these are only
set if the values themselves are set (rather than always being set,
possibly to an empty value, if datadog is enabled).
=> support datadog agent uds filepath

README.md, templates/web-ingress.yaml, values.yaml
Fixes #264  .
* Set web.ingress.ingressClassName to choose IngressClass
=> Support defining which ingressClass to use.

README.md, templates/_helpers.tpl, values.yaml
added in concourse/concourse#7487
=> Add trace flags to worker

templates/worker-deployment.yaml, templates/worker-secrets.yaml, templates/worker-statefulset.yaml
This PR provided some bug fixes related to #211. 
* use consistent mechanism to retrieve certificates in  `worker-secret.yml`
removal of worker.additionalCertificates should have been done with 43483576525c8fab2e5af1f3ff41a039b122d433  (included in #244). But it still present in `worker-secret.yml`.
* use `worker.certsPath` defined in `values.yml` instead `worker.workerCertsPath` (undocumented and not use anywhere else).
https://github.com/concourse/concourse-chart/blob/6b13c2077bcdede6ef1615d22eef9d36307e70e7/values.yaml#L2304-L2307
Which branch are you merging into? 
> This section is intended for the core maintainers only, to track review …
=> Fix worker custom certificats support

templates/web-deployment.yaml
Complete https://github.com/concourse/concourse-chart/pull/220
=> Fix indent of initContainers in web-deployment

templates/worker-deployment.yaml, templates/worker-secrets.yaml, templates/worker-statefulset.yaml
https://github.com/concourse/concourse-chart/issues/211
* add subPath so it won't remove exsiting files in worker.certsPath
* make name more consistant
=> update worker additional certs config

templates/web-deployment.yaml, values.yaml
Related concourse/concourse#7876
=> Add --pause-pipelines-after flag

templates/web-deployment.yaml, values.yaml
For env var added in https://github.com/concourse/concourse/pull/7928
=> add aws ssm shared secret template env var

templates/web-deployment.yaml, values.yaml
Related to https://github.com/concourse/concourse/pull/8183
=> Add noInputContainerPlacementStrategy.

templates/web-deployment.yaml, templates/web-podsecuritypolicy.yaml, templates/web-servicemonitor.yaml, values.yaml
refer to https://github.com/concourse/concourse/pull/8324
=> add vault srv lookup

templates/web-deployment.yaml, values.yaml
refer to https://github.com/concourse/concourse/pull/8353
=> add oidc diable get userinfo flag

Chart.lock, Chart.yaml, README.md, templates/_helpers.tpl, templates/web-podsecuritypolicy.yaml, templates/worker-podsecuritypolicy.yaml, templates/worker-policy.yaml, values.yaml
update concourse chart to support postgresql chart v11
refer to https://github.com/concourse/concourse-chart/issues/290
=> bump postgres chart to v11

README.md, templates/web-deployment.yaml, values.yaml
Would like to provide labels not only to `.spec.template.metadata.labels` but also `.metadata.labels`.
Add values from `.Values.web.labels` to web-deployment's `.metadata.labels`.
=> feat: add web labels to deployment metadata

templates/web-deployment.yaml, values.yaml
Add the new ATC option introduced by https://github.com/concourse/concourse/pull/8494.
=> Add CONCOURSE_CHECK_CONTAINER_PLACEMENT_STRATEGY.

templates/web-podsecuritypolicy.yaml, templates/worker-podsecuritypolicy.yaml
Fixes https://github.com/concourse/concourse-chart/issues/310#issuecomment-1285342336.
policy/v1 doesn't contain PodSecurityPolicy, so this chart fails to install for all users that create a psp from the chart.
Revert relevant lines from https://github.com/concourse/concourse-chart/commit/ade9143b9c3d4c427fd9ddc71f7a3db377f4cdf1
=> Use v1beta1 apiVersion for PSPs

templates/_helpers.tpl, values.yaml
=> Add worker containerd config to 7.9.x

templates/web-deployment.yaml, values.yaml
refer to https://github.com/concourse/concourse/pull/8709.
=> Add num-goroutine-threshold configuration

README.md, templates/web-deployment.yaml, values.yaml
Account for changes introduced in https://github.com/concourse/concourse/pull/8899
Adds support for a newly introduced env var
* web.vault.tokenPath
=> Vault token path

templates/_helpers.tpl
Fixes # .
fixing an helm error to be consistent with [instructions](https://concourse-ci.org/concourse-worker.html#p2p-worker-configuration)
* 
* 
*
=> add quote to `concourse.worker.baggageclaim.p2pInterfaceFamily`

templates/web-deployment.yaml
=> fix vault conditional for web-deployment

templates/worker-statefulset.yaml
This should fix https://github.com/concourse/concourse-chart/issues/360
=> Fix cleanup of the worker workDir in the init container

templates/_helpers.tpl, templates/web-deployment.yaml, values.yaml
Related to concourse/concourse#9147
* Add `CONCOURSE_STRICT_TRANSPORT_SECURITY`
* Add `CONCOURSE_CONTAINERD_PRIVILEGED_MODE`
* Remove `CONCOURSE_POSTGRES_BINARY_PARAMETERS` because we switched to pgx from lib/pq
=> Update flags for next release

README.md, templates/web-api-svc.yaml, values.yaml
Rebase and re-submission of #326
=> Enable Port Name overrides on web-api-service - Ibrahimparvez2/master

Chart.lock, Chart.yaml
* Update postgres to latest minor Version. 
=> bump postgres version
