Chart.yaml, README.md, templates/worker-statefulset.yaml, values.yaml
Previously, we were making incorrect use of quotes in the script that
was used to remove the state that was left behind from previous runs
(see https://github.com/concourse/charts/issues/6)
This commit is a backport of the helm/charts#17920, including a bump to
the default versions so that we use the latest ones.
=> worker: fix misuse of quotes + default image bump

LICENSE.md
Make the LICENSE as same as CONCOURSE LICENSE by copying from the repo: github.com/concourse/concourse
Signed-off-by: Bin Ju <bju@pivotal.io>
=> add license file to this repo

Chart.yaml, README.md, templates/web-deployment.yaml, templates/worker-statefulset.yaml, values.yaml
* In 5.7.1, we added this configuration option as part of
[#4707](https://github.com/concourse/concourse/pull/4707)
Co-authored-by: Ciro S. Costa
Signed-off-by: Denise Yu <dyu@pivotal.io>
=> Add CONCOURSE_GARDEN_REQUEST_TIMEOUT config

.github/pull_request_template.md, CODE_OF_CONDUCT.md
Until we get more automation around checking the PR's, similar to what
`helm/charts` has, this PR template should ease the burden of reminding
others what needs to be updated when updating the helm chart.
Signed-off-by: Taylor Silva <tsilva@pivotal.io>
=> Add PR template and Code of Conduct

README.md
This updates the tldr with the following:
* Repo add command (stable is being deprecated)
* Updated the install to point to ```concourse/concourse```
=> Update readme include concourse repo and updated install location tldr

Chart.yaml, README.md, templates/worker-statefulset.yaml, values.yaml
Previously, there was no way of having two releases of `worker` sharing
the same set of labels in their hard anti affinity rules given that we'd
always put a set that's release specific.
That meant that if one had a set of workers deployed through a release,
say, `release-1`, and another set of workers deployed through another
release, say, `release-2`, these would never be able to leverage the
same set of labels in their anti affinity rules as they'd have `release`
and `app` (label keys) set with values that would match `release-1` and
`release-2`.
The implication of that is that it becomes impossible guarantee the
inability of placing two concourse workers in the same node (on a shared
pool).
With the addition of `worker.hardAntiAffinityLabels` one is now able to
customize that set.
For …
=> worker: add hard anti affinity labels config

requirements.lock, requirements.yaml, templates/_helpers.tpl, templates/web-deployment.yaml, templates/web-ingress.yaml, templates/worker-statefulset.yaml
add support for kuberntes 1.16 and up
also backwards compatible.
see #9 
dupe of https://github.com/helm/charts/pull/18557
i also needed to define the selector see https://github.com/helm/charts/issues/7726
have not tested an upgrade scenario.
see selector issues
=> kubernetes support for 1.16 and up

README.md, templates/web-deployment.yaml, templates/web-secrets.yaml, values.yaml
Addresses https://github.com/concourse/concourse-chart/issues/34.
Helm packaging and the Concourse binary's `web` configs have drifted since a few PRs got merged in. This reconciles some of that!
* Add configs for Microsoft auth connector
* Add configs for Conjur credential manager
* ~Add config for Vault namespace~ looks like Jamie and Zoe did this in #33
=> Add microsoft auth and conjur creds manager configs

templates/web-configmap.yaml, templates/web-deployment.yaml, values.yaml
We were seeing `k8s-check-helm-params` failures like https://nci.concourse-ci.org/teams/main/pipelines/concourse/jobs/k8s-check-helm-params/builds/29.
Adds the following configuration parameters to the helm chart:
* `--config-rbac`
* `--vault-namespace`
* `--main-team-cf-space-with-any-role`
* `--main-team-cf-space-with-developer-role`
* `--main-team-cf-space-with-auditor-role`
* `--main-team-cf-space-with-manager-role`
There is also a slight structural change in that now the web deployment has an
associated configmap that is used to mount configuration files that are not
secrets. As of now, this consists of only the main team config and RBAC config
files.
=> add some missing flags for v5.8.0 release

values.yaml
Closes #46 
We got user feedback that it was unclear how these values were meant to
be passed to the helm chart. Users were trying to pass in a YAML object instead of a multi-line YAML string.
This PR adds examples to the default values.yaml which should make this clearer for
users of the chart.
=> Add examples for RBAC and mainTeam config

README.md
Fixes #48 by adding the Concourse binary method as the first way of
generating secrets. Updates the ssh-keygen method by adding the `-m`
flag to specify what format the key needs to be in.
Removed a reference to this issue:
https://github.com/helm/charts/issues/13019
Issue was fixed and therefore not relevant to the chart anymore.
=> Update secrets generation section of README

templates/web-deployment.yaml, values.yaml
makes the changes from https://github.com/concourse/concourse/pull/5043 configurable
ps.: this is not yet available on "released" versions of concourse (e.g., it'll arrive on 6.0) - am I doing this right, @taylorsilva ?
add `concourse.web.tracing.*` values to `values.yaml`, as well as the `web-deployment.yaml` template.
- ~[ ] Variables are documented in the `README.md`~ the flags are concourse-specific
---
thankss!
=> make tracing flags configurable

templates/web-deployment.yaml
when adding the tracing configuration, I mistakenly types `{{-end}}`
(instead of `{{- end }}`. shame on me.
tested with `concourse/concourse`'s `topgun/k8s` to make sure we
got it right.
=> web-deployment: fix conditional syntax

templates/web-configmap.yaml
Fixes #50 and #62
We only want to create the config map if either of the two values have
been set. This also caused installs using the default values.yml to fail 
because we would try to create an invalid config map.
Tested all four ways of setting the config map:
- nothing set
- main team config
- rbac
- main team and rbac
All worked correctly. Here's the configmap for when both main team and rbac config are set:
```
$ kubectl describe configmaps bbb-web
Name:         bbb-web
Namespace:    default
Labels:       app=bbb-web
chart=concourse-9.0.0
heritage=Helm
release=bbb
Annotations:  <none>
Data
====
config-rbac.yml:
----
owner:
-SetTeam
main-team.yml:
----
roles:
- name: owner
local:
users: ["test"]
```
> Are the following items included as part of this PR? Please delete checkbox items …
=> Wrap config map in if-checks

Chart.yaml, README.md, templates/web-servicemonitor.yaml, values.yaml
Signed-off-by: Yannick Kint <yannick.kint@gmail.com>
Make it possible to use the prometheus-operator in combination with this chart.
* Add ability to enable the creation of a serviceMonitor object for the prometheus-operator. The serviceMonitor will make sure the metrics are scraped by prometheus.
=> Add serviceMonitor object to the chart

values.yaml
Fixed the validation issues preventing helm v3 from installing the chart.
*  Set default value for configRBAC to empty string
*  Set default value for mainTeam config to empty string
=> Fixed helm v3 chart validation issues

Chart.yaml, templates/web-deployment.yaml, templates/web-secrets.yaml
Backports concourse/concourse-chart#79 to the 5.5.x series.
* If Lets Encrypt is enabled, it takes precedence over any supplied cert.
* This avoids a panic/crash when both options are provided.
=> 5.5.x: LetsEncrypt takes precedence over supplied cert

Chart.yaml, templates/web-deployment.yaml, templates/web-secrets.yaml
With the implementation of auto certs in concourse, it will panic when user enable lets encrypt and providing certs at the same time. 
Disable web tls certs when lets encrypt is opt in.
=> disable web tls certs when lets encrypt is enabled

Chart.yaml, templates/worker-statefulset.yaml, values.yaml
Related to https://github.com/concourse/concourse/pull/5297
So concourse chart could be used to deploy worker with Containerd backend
=> Allow deploying worker with Containerd backend

Chart.yaml, values.yaml
concourse 5.5.9 -> 5.5.10
chart 8.2.10 -> 8.2.11
=> bump concourse app version and chart version

Chart.yaml, README.md, templates/web-deployment.yaml, templates/worker-statefulset.yaml, values.yaml
N/A
We are currently maintaining a fork of this chart to add 10 lines of yaml as an `initContainer` to the web pods, this change will make this no longer required. 
> What are the changes included in this PR? Feel free to add as many lines as needed below.
* Adding optional `initContainers` to worker pods
* Adding optional `initContainers` to web pods
=> Allow extra initContainers for both web and worker pods.

Chart.yaml, templates/_helpers.tpl
Signed-off-by: Paul Czarkowski <username.taken@gmail.com>
When Helm is unable to talk to a kube cluster it picks a default
kube version to use for Capabilities.  This allows helm template
and similar commands to work.
However this chart keys off .Capabiltities.KubeVersion.GitVersion, the
which sometimes has a `v` prefix and thus the logic
above the semver tests and assumes its a really old cluster.
This results in deprecated kube apis being used which fails on
clusters newer than 1.16.
This PR Updates the helpers to remove any `v` from the gitversion string that is returned.
=> [bugfix] kubeversion lookup when helm offline

Chart.yaml, templates/web-deployment.yaml, templates/worker-statefulset.yaml
follow suggestion from helm docs
https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
since changes for public worker keys did not get applied until pod restart
was triggered manually
Co-authored-by: Hans Mündelein <hans@oss.volkswagen.com>
Signed-off-by: Hannes Hasselbring <hannes@oss.volkswagen.com>
none
When changing a secret or configMap with `helm upgrade` the changes are not applied until manually restarting the pod.
* Following the [helm tips and tricks](https://helm.sh/docs/howto/charts_tips_and_tricks/\#automatically-roll-deployments), a hash of the generated configMaps/secrets is added
as an annotation, which leads to an automated restart of affected pods.
=> Roll pods on config/secets changes

Chart.yaml, templates/web-rolebinding.yaml
The optional creation of team namespaces was not very optional, as the web rolebindings hardcoded assumed their presence. This commit fixes this.
Fixes helm/charts#18008
Fixes concourse/concourse-chart#3
=> fix createTeamNamespaces

Chart.yaml, templates/worker-statefulset.yaml
The indention of a toYaml function call seems to be indention dependent and insertion of annotations on workers recently got moved one indent in. ( see https://github.com/concourse/concourse-chart/commit/b1b0d0306bfb5061297b53ae1fcdaffe2b98a3a9 )
This leads to illegal kubernetes yaml being generated when you add annotations.
* Remove indent of annotation insertion
=> Fix indention of annotations on workers.

Chart.yaml, README.md, templates/web-deployment.yaml, values.yaml
It is currently not possible to change the way concourse-web is started without building a new docker image with a custom entrypoint.
Allow to override the docker image entrypoint by specifying a `command`.
Allow to change the default `args` of the `command`
=> web: allow to override command and args

Chart.yaml, templates/web-deployment.yaml, values.yaml
Contributes to concourse/concourse#5421.
I decided to make the `values.yaml` entry be the plural "limits" becase we
will definitely be adding support for specifying multiple limits separated by
commas in the future, and I don't want to have to change the parameter name at
that point.
=> add `--concurrent-request-limit`

Chart.yaml, README.md, templates/web-podsecuritypolicy.yaml, templates/web-role.yaml, templates/web-rolebinding.yaml, templates/worker-podsecuritypolicy.yaml, templates/worker-role.yaml, templates/worker-rolebinding.yaml, values.yaml
add parameters to enable the creation of podsecuritypolicy
Signed-off-by: Yannick Kint <yannick.kint@gmail.com>
Concourse pods need some privileges at the moment (e.g. worker pods need to run as root, in a privileged container), in clusters with a default podsecuritypolicy that restricts this, a custom psp object is needed for concourse.
* Add option in the values.yaml to enable the creation of psp objects
* When rbac.create is also enabled, make sure correct rbac objects are created so pods can use the psp objects
=> add parameters to enable the creation of podsecuritypolicy

values.yaml
The values used to set authorizedKeys fall under `web` and `secerts`.
Search for `keys` in the values.yaml or look in the web-deployment.yaml
file and search for:
- CONCOURSE_TSA_AUTHORIZED_KEYS
- CONCOURSE_TSA_TEAM_AUTHORIZED_KEYS
You can then see which keys in values.yaml are used to populate the TSA
authorizedKeys.
Fixes #16
This variable was never actually documented.
=> The authorizedKeys values is not used at all.

templates/web-deployment.yaml, values.yaml
The static worker fields are no longer used (part of v6.2.0)
Also updated the max checks per second description
=> v6.3.0 release branch

Chart.yaml, README.md, templates/web-servicemonitor.yaml, values.yaml
This PR allows custom metric relabeling rules to be applied to the web-servicemonitor resource. This allows the user to consolidate duplicate metrics generated when running the web service in HA. I've left an example on how to do this in the values.yaml comments
* Add variable `web.prometheus.ServiceMonitor.metricRelabelings`
=> Servicemonitor metric relabeling

templates/web-deployment.yaml, values.yaml
> https://github.com/concourse/concourse/discussions/5738
Fix the lookup template example.
* Fix the lookup template example.
=> Fix the vault lookup template env value 

README.md, templates/web-servicemonitor.yaml, values.yaml
This change allows to set additional labels for serviceMonitors.
As the prometheus-operator allows to discover serviceMonitors by label, the ability to set additional labels in the values.yaml helps with this strategy.  
* Append labels to the serviceMonitor object if defined 
=> ServiceMonitor: add additional labels

templates/_helpers.tpl
The "fullnameOverride" value does not work. It is not implemented in the Concourse Helm Chart.
So instead of using the Helm Chart release we can override it for resources:
--set fullnameOverride=$(NAME)
--set postgresql.fullnameOverride=$(NAME)-postgresql \
=> Fix fullnameOverride not settings fullname of resources

README.md
kube-lego has been deprecated in favour of cert-manager, update the README to reflect that
=> Don't link to deprecated tools

templates/web-deployment.yaml, values.yaml
This feature is now always on since the RFC was merged.
=> Remove the enableArchivePipeline flag

templates/web-deployment.yaml, values.yaml
`CONCOURSE_TSA_GARDEN_REQUEST_TIMEOUT` was added in https://github.com/concourse/concourse/pull/5845. This PR allows that value to be configured in the chart.
=> web: add CONCOURSE_TSA_GARDEN_REQUEST_TIMEOUT

.gitignore, README.md, templates/_helpers.tpl, values.yaml
Part of the PR concourse/concourse#5911, which addresses issue concourse/concourse#5407.
* replace useContainerd and useHoudining with runtime.type
* remove redundant garden env vars
* add support for finalized containerd flags 
To test this I tried the following values in the `values.yml`
I then ran `helm template` and got the following output:
=> add support for new containerd flags

values.yaml
Unused `concourse.web.vault.clientToken` value can lead to misconfiguration - I expected this value to be the one that configures the client token but it is actually `secrets.valueClientToken`
Delete unused value
=> Remove unused vault.clientToken value

values.yaml
Partially fixes #145.
* Refer to the key in `values.yml` where local users are set (rather than the eventual name of the Kubernetes secret)
* Add a link to Concourse docs where list format is described more fully
=> Clarify comments in values.yml

templates/web-ingress.yaml
Signed-off-by: Dr Colin Kong <colin.kong@playtech.com>
Fixes # .
web-ingress does not use "fullnameOverride" to find web service.
Tested both "--set fullnameOverride=$(NAME)" and without. Both ingress works
=> Fix web-ingress for fullnameOverride

values.yaml
Fix linter failures from the `lint-and-install-test` in the helm pr pipelines https://ci.concourse-ci.org/teams/main/pipelines/helm-prs/jobs/lint-and-install-test/builds/138. It is fixed in the `dev` branch but `master` branch also needs the fix too for prs to get merged into the branch.
rbac.authorization.k8s.io/v1beta1 -> /v1
It looks like most of v1beta1 was deprecated in v1.17 and will be removed by v1.22 https://godoc.org/k8s.io/api/rbac/v1beta1#ClusterRole
> This section is intended …
=> rbac.authorization.k8s.io/v1beta1 -> /v1

templates/_helpers.tpl
N/A
Fixes an issue highlighted when we ran our hrval linter
* Add quotations around `concourse.worker.garden.maxContainers` value 
=> fix: Add quotations to garden max containers

README.md, templates/web-deployment.yaml, values.yaml
Since concourse/concourse#5652, it is possible to send a `SIGHUP` signal to the TSA to reload worker authorized keys without restarting the concourse server.
In order to use that feature with the concourse helm chart, one correct Kubernetes way to achieve that is to add a sidecar container responsible to update the team authorized keys file from whatever source, and then send the `SIGHUP` signal to Concourse in order to take the update into account.
That being said, to be able to send a `SIGHUP` signal between containers within a pod, the `shareProcessNamespace` field of `v1.PodSpec` needs to be set to `true`.
This PR implements a new parameter in the chart in order to enable that process namespace sharing capability for the web component.
At Cycloid, we participated in the implementation …
=> Allow enabling process namespace sharing for the web nodes

README.md, templates/web-serviceaccount.yaml, templates/worker-serviceaccount.yaml, values.yaml
Fixes #173 
* Adds annotations variables for both worker and web since they might have different use cases for annotations, these are defined inside the values.yaml and will be rendered(if there are any) into chart at runtime.
* Adds the annotation include statements into the web and worker service account template files. 
Merging to master should be okay (?) happy to move to dev if need be, as I mentioned i've already worked around this by creating my own service accounts but would be nice to have this natively supported.
=> Add ability to define annotations for web/worker Service accounts

templates/web-serviceaccount.yaml, templates/worker-serviceaccount.yaml
I submitted a change to the Service accounts but it appears the annotations indentations were malformed, and it didn't show up locally when trying out the changes so not too sure how that happened, I have an auto linter on save so it probably screwed me over.
* Update annotation indentation so it actually works.
=> Fixing indentation for annotations

templates/NOTES.txt
Fixes #179 .
The tutorials in NOTES was throwing a 404, changed to examples - https://concourse-ci.org/examples.html
* change link to examples https://concourse-ci.org/examples.html
=> Fix tutorials link in helm NOTES

templates/web-deployment.yaml
There was a typo in the 6.7.2 chart that's now been fixed.
=> Merge latest 6.7.x to master

templates/web-deployment.yaml, values.yaml
Applies only to the `web` container on the `web-deployment` pod, useful for stuff like attaching a live debugger to the process.
=> add ability to configure SecurityContext for web container

templates/_helpers.tpl, templates/web-deployment.yaml, templates/worker-deployment.yaml, values.yaml
Fixes CI 
Adds the following flags/envs:
```
CONCOURSE_BAGGAGECLAIM_P2P_INTERFACE_FAMILY
CONCOURSE_BAGGAGECLAIM_P2P_INTERFACE_NAME_PATTERN
CONCOURSE_ENABLE_P2P_VOLUME_STREAMING
CONCOURSE_P2P_VOLUME_STREAMING_TIMEOUT
```
=> Add baggageclaim p2p volume streaming flags

README.md
Fixes the usage of the vault secret provider in the readme 
* change the readme to make the vault section similar to the credhub one
=> Fixed the usage of vault

README.md, values.yaml
Fixes #160 160
* Change default value of web.clusterip
- [X ] Variables are documented in the `README.md`
- [dev] Which branch are you merging into?
=> fixes 160 clusterip values

templates/_helpers.tpl, templates/web-deployment.yaml, templates/worker-deployment.yaml
implements https://github.com/concourse/concourse-chart/issues/194
BLOCKED: we learned the `concourse migrate` does not automatically migrate to the latest db version. You actually need to pass in one of the following flags:
```
--current-db-version
--supported-db-version
--migrate-db-to-version
```
We would need to script the migration process now in order to use this command. We're thinking of PR'ing a change concourse/concourse to make the migrate command migrate to the latest version by default or add a flag that will do that for us.
This PR should go into `dev` branch if we don't do the scripting option.
=> Run db migrations in init container

Chart.yaml, templates/web-deployment.yaml, values.yaml
* adds a flag for setting `CONCOURSE_OIDC_SKIP_EMAIL_VERIFIED_VALIDATION`
* bumps chart/app version and bumps the tag
=> add flag for skipping email verification

templates/_helpers.tpl
Fixes #204
The ingress resource was moved to a new API group, with a full cutover starting in 1.22. Moved from `networking.k8s.io/v1beta1` to `networking.k8s.io/v1`.
Based on [this comment](https://github.com/kubernetes/kubernetes/issues/94761#issuecomment-691982480) the new API group is only applied when the cluster version is >=1.20, which is when k8s starts reading from the stable api group instead of the beta api group for the ingress controller.
> This section is intended for the core …
=> Fix ingress API group for >1.20 k8s

templates/web-ingress.yaml
This commit adjusts the ingress template to be compatible to
api-version networking.k8s.io/v1.
See also: #204
related to: #204 
Deploying to a k8s > v1.20 is broken because of an incompatible ingress-spec.
`helm upgrade|install` throws following error:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "servicePort" in io.k8s.api.networking.v1.IngressBackend]
helm.go:81: [debug] error validating "": error validating data: [ValidationError(Ingress.spec.rules[0].http.paths[0].backend): unknown field "serviceName" in io.k8s.api.networking.v1.IngressBackend, …
```
=> Fix template for ingress API v1

Chart.yaml, templates/web-deployment.yaml
Only one `volumes` entry is allowed for a pod spec, and it already
exists for the web deployment, and already has the same keys and values
as the newly introduced `volumes` section to the initContainer that
provides the migration work. 
* This commit removes that section, which is invalid anyway, because `volumes` must exist at the `spec` level, not under `initContainers`.
=> Remove bad volumes section from concourse.web.initContainers

templates/web-api-svc.yaml
Changing atcNodePort to NodePort and atcTlsNodePort to tlsNodePort
Signed-off-by: Rui Yang <ryang@pivotal.io>
Fixes #212 
*  Fixing typos for atcTlsNodePort and atcNodePort for web-api-svc.yaml file
- [x ] Variables are documented in the `README.md`
=> Fixing typo error on web-api-svc.yaml

templates/web-deployment.yaml, values.yaml
Fixes #222 
Allow setting `CONCOURSE_VAULT_AUTH_PARAM` when using `CONCOURSE_VAULT_AUTH_BACKEND=ldap`
=> fix: provide CONCOURSE_VAULT_AUTH_PARAM for ldap backend

templates/web-prometheus-svc.yaml, values.yaml
Fixes #213  .
Change prometheus service template to allow deployed as NodePort, ClusterIP or LoadBalancer service. 
remove "None" value for cluster IP in values.yml. refer to #163.
* 
* 
*
=> allow deploy prometheus with different service type

Chart.lock, Chart.yaml
Breaking changes: https://github.com/bitnami/charts/tree/master/bitnami/postgresql#to-1000
tldr: uses helm api v2, same as our chart. Some name changes like
master -> primary, slave -> readReplicas
We should make this a major bump of the chart and link to the bitnami readme above
=> Breaking: Bump postgres chart version to 10.3.13

templates/web-api-svc.yaml, templates/web-worker-gateway-svc.yaml, values.yaml
fixes #187
I verified that when no value is set that `clusterIP` does not render. When a value is set it does render.
=> Don't set cluster ip if no value is specified

README.md, templates/required-check.yaml, templates/web-ingress.yaml, values.yaml
Allows for adding additional, earlier paths to web-ingress. The impetus
for this change is to allow for setting up an HTTP -> HTTPS redirect
with AWS ALBs. For example:
```yaml
metadata:
annotations:
alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}'
spec:
rules:
- host: "concourse.example.com"
paths:
- path: '/*'
backend:
serviceName: 'ssl-redirect'
servicePort: 'use-annotation'
- path: '/*'
backend:
serviceName: {{ template "web.fullname" . }}
servicePort: "atc"
```
Reference: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.1/guide/tasks/ssl_redirect/
- `master` is for changes related to the current release of the `concourse/concourse:latest` image and should be good to …
=> Add earlier paths option for web-ingress

README.md, templates/worker-deployment.yaml, templates/worker-secrets.yaml, templates/worker-statefulset.yaml, values.yaml
Fixes #https://github.com/concourse/concourse-chart/issues/211.
User will be able to config a .pem file that contains additional certs that could be added to worker certs pool by specifying a path (default to /etc/ssl/certs/worker-certs.pem). Notice the path has to be a file so it could be additional other than replacing entire /etc/ssl/certs directory.
=> Allow adding custom worker certs that all container can inherit

templates/web-deployment.yaml, values.yaml
#223 introduced a breaking change - before, when the vault backend was set to approle, we'd set `CONCOURSE_VAULT_AUTH_PARAM`.  now, it's only set if `useAuthParam` is explicitly set to true, since it defaults to false. this means that upgrading from 15.0.x -> 15.1.x unset that param, unless you knew to enable `useAuthParam` (which wasn't documented in the release notes).
it seems more sane to set the auth param if either you explicitly opt-in (by enabling `useAuthParam`) OR if you set the vault auth param in the secret, and didn't explicitly opt-out by setting `useAuthParam` to false
* No default for `.Values.concourse.web.vault.useAuthParam` - distinguish between unset and `false`
* Set `CONCOURSE_VAULT_AUTH_PARAM` from secret if `Values.concourse.web.vault.useAuthParam` is set to true …
=> default `CONCOURSE_VAULT_AUTH_PARAM` to set if the corresponding secret is set

values.yaml
which is detect and will use overlay most likely. naive is really slow
once you have large files involved.
We should use the defaults in the binary instead of setting our own in the chart.
=> Use the default baggageclaim driver set in the concourse binary

README.md, templates/_helpers.tpl, values.yaml
add the `CONCOURSE_CONTAINERD_ALLOW_HOST_ACCESS` flag to chart.
part of: concourse/concourse#6720
=> Add flag to allow host access on containerd

README.md, templates/web-deployment.yaml, templates/worker-deployment.yaml, templates/worker-statefulset.yaml, values.yaml
this add new (optional) `web.priorityClassName` and `worker.priorityClassName` values for configuring the PodPriority of the web/worker pods.
See: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority
when attempting to run concourse workers that consume a large percentage of a node's resources you can come up against scheduling issues due to poor bin-packing of pods on to nodes.
setting pod priorities can be useful in this case, allowing the scheduler shuffle things around and evict pods to make room.
=> allow configuring priorityClassName for pods

templates/_helpers.tpl
The helm chart check for concourse.worker.garden.dnsProxyEnable assumes the default value of this variable is false.  However, the underlying env var CONCOURSE_GARDEN_DNS_PROXY_ENABLE defaults to true in the container.
In short, changing this value to false has no effect on the worker deployment, and setting to true sets an env var to true that is already default true (in the Dockerfile), so again, no effect.
* Change the boolean check in the helper to `not(kindIs "invalid")` which passes when the value has any actual value (true or false)
=> Fix broken .Values.concourse.worker.garden.dnsProxyEnable helper

README.md, templates/worker-statefulset.yaml, values.yaml
In some cases (like bare metal k8s) you want to assign label selector to claim template to be able to select among different manually created PVs.
Selector field is added to pvc template inside worker sts template. By default corresponding value is commented in values.yaml.
- [master] Which branch are you merging into?
=> Pv selector

templates/web-deployment.yaml, values.yaml
Port over commit to add datadog agent uds filepath field to release/7.4.x branch
Fixes https://ci.concourse-ci.org/teams/main/pipelines/release/jobs/k8s-check-helm-params/builds/3?vars.version=%227.4.x%22
=> support datadog agent uds filepath

README.md, templates/web-deployment.yaml
Add volume/volume mount for sending datadog dogstatsd metrics over unix domain socket (uds) when user sets a value for `agentUdsFilepath`.
Signed-off-by: Jennifer Hwang <jmhwang7@gmail.com>
This matches setup instructions by Datadog here: https://docs.datadoghq.com/developers/dogstatsd/unix_socket/?tab=kubernetes#using-origin-detection-for-container-tagging
* Adds read-only volumeMount for the socket
* Adds hostPath volume for the socket
* Adds readme docs for `web.datadog.agentUdsFilepath` …
=> Add volume/volume mount for sending datadog metrics over uds

templates/worker-horizontal-pod-autoscaler.yaml, values.yaml
This PR adds the behavior field to the worker HPA template.  Once added the behavior field will allow users to adjust scale down and scale up windows beyond the default kubernetes settings.
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#default-behavior
* Add spec.behavior field to worker HPA to allow for custom scale behavior
=> Add HPA autoscaling behavior field

values.yaml
Add the key to values.yml with example value string. Not sure why it was missing in the first place.
=> add hostedDomains to oidc auth values config

values.yaml
Fixes #279  .
Remove those example values that causes extra log messages. So it will be same config as they are in `concourse.web.tracing`.
=> remove jaeger config default values

templates/worker-deployment.yaml, templates/worker-statefulset.yaml, values.yaml
Using replicas and HPA at same time can causes some troubles when reapplying some resources since it reset to replicas number.
Fixes # .
Make `replicas` conditional on using HPA for workers
* Added condition to replicas in worker deployment
* Added condition to replicas in worker statefulset
* Fix some indentation issue in example vars
=> Ignore replicas number in Deployment/Statefulset when using autoscaling

Chart.yaml
It is not an issue with the chart. We just need a new Concourse version with bug fixes.
Concourse `7.7.0` (the latest version provided by this chart) has [this terrible pipeline archiving bug](https://github.com/concourse/concourse/issues/8167). We need a version that fixes that bug, and that version is `7.7.1`.
* Bump chart version to `16.1.22` (from `16.1.21`)
* Bump concourse version to `7.7.1`
`master`
=> Bump concourse version to 7.7.1

CHANGELOG.md, values.yaml
refer to https://github.com/concourse/concourse-chart/issues/290
=> update changelog with v17 info

Chart.yaml
```
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Error: can't get a valid version for repositories postgresql. Try changing the version constraint in Chart.yaml
```
When running release pipeline for concourse 6.7.x, above error shows up in [k8s-smoke job](https://ci.concourse-ci.org/teams/main/pipelines/release/jobs/k8s-smoke/builds/1?vars.version=%226.7.x%22). Old version of postgresql chart does not exist anymore on binami postgresql chart repo.
=> bump postgresql chart as old version not exists

templates/web-deployment.yaml, values.yaml
the actual Dex configure has never worked
and it is now [removed](https://github.com/concourse/dex/commit/67d9142887361d1cc2ea125f59f0f244449742a7) from concourse/dex
=> remove oidc.hostedDomains

templates/web-deployment.yaml, values.yaml
odic.hostedDomains is not used in Dex code base and it got cleaned up in latest Dex release. So we need to update Concourse code base accordingly.
=> remove not used oidc --hosted-domains flag

templates/_helpers.tpl, values.yaml
for oci-hooks-dir and seccomp-profile
refer to https://github.com/concourse/concourse/pull/8044
=> add worker containerd config

values.yaml
Currently some of the values intended to be used by the PostgreSQL-subchart do not have the correct structure. The subchart, as it is currently used, expects them at `(.values).primary.persistence` (checked both the in-use version `11.9.8` and the current version `12.1.9`) but they are passed along simply at `(.values).persistence`. The relevant part of the PostgreSQL chart documentation can be found at https://artifacthub.io/packages/helm/bitnami/postgresql#postgresql-primary-parameters.
*  Move the value `postgresql.persistence` to `postgresql.primary.persistence`
- `dev` is for changes related to the next release of Concourse (aka unpublished code …
=> Fix postgreSQL persistence chart-values

README.md, templates/worker-statefulset.yaml, values.yaml
> This PR adds support for applying labels to the PVCs created by the worker's statefulset, via volumeClaimTemplates. In some backup regimes, items are included/excluded from backups by virtue of their labels.
Closes & replaces: https://github.com/concourse/concourse-chart/pull/322.
* Add a new chart value, `persistence.worker.labels`
=> feat: support labels on worker volumeClaimTemplate

templates/worker-statefulset.yaml
Decouples the extraInitContainers and cleanUpWorkDirOnStart variables. Currently it is impossible to have an extraInitContainer without also having the init-rm container
Slightly changed conditionality around the initContainers in the statefulset yaml
merging into **master**
=> Decoupling init-rm initContainer and extra initContainers

README.md
See here for context: https://github.com/concourse/concourse-chart/pull/338/files/4f7f97e739751781514eb6f40cb63ce78b41b2ed#r1297147298
Quick summary: Rui Yang believes this is a regression or an oversight he made, and asked me to revert it.
=> revert: regression in README, context below

templates/worker-horizontal-pod-autoscaler.yaml
The `autoscaling/v2beta2` API is deprecated in v1.23+, unavailable in v1.26+
* Use `autoscaling/v2` if Kubernetes version is >= 1.23
=> Update autoscaling API version

README.md, templates/web-deployment.yaml, templates/worker-deployment.yaml, values.yaml
Allow user to optionally configure annotations on the worker and web Deployments via Chart values. This could be used (for my example) with integrations for ImageStreams in OKD/OpenShift.
---
While Annotations generally have a wide variety of uses, I found the need for this feature while working with [OKD/OpenShift's ImageStreams](https://docs.openshift.com/container-platform/4.13/openshift_images/image-streams-manage.html). ImageStreams will modify Deployments according to a user's configuration (via Deployment Annotations) to use specific digests or even the built-in registry.
* Allow users to specify Annotations to the Web/Worker Deployments via the new `deploymentAnnotations` field under `web` and `worker` respectively.
- `master` is for changes related to the current release of the …
=> Add support for deploymentAnnotations

README.md, templates/worker-deployment.yaml, templates/worker-statefulset.yaml, values.yaml
- https://github.com/concourse/concourse-chart/issues/267 (This is directly related, but no changes resulted from the issue)
We we were looking to implement p2p streaming for workers; however, there was no support for adding additional ports for worker communication. 
- adds ability to add additional ports to worker pods
=> feat: support adding additional ports to workers

Chart.yaml, templates/web-deployment.yaml
Signed-off-by: David Young <davidy@funkypenguin.co.nz>
Fixes # .
In the concourse-web pod, the primary container supports a user-configurable securityContext. However, the "migration" initContainer does not, which causes automated security assessement tools (in my case, Fairwinds Polaris) to fail the entire pod.
This PR simply adds the same securityContext used for the concourse-web primary containier, to the migration initContainer
> This section is intended for the core maintainers only, …
=> Add securityContext to concourse-web initContainer

templates/web-deployment.yaml
Only set the AWS variables if the enabled flag is true for secrets lookup
Fixes #348.
* only set AWS region variable if AWS Secrets Manager or Ssm integration is enabled
=> fix(aws-secrets): use AWS secrets only if enabled

templates/_helpers.tpl, values.yaml
Adding env vars from https://github.com/concourse/concourse/pull/8801
=> Add containerd IPv6 env vars

templates/worker-prestop-configmap.yaml
no
In our productive k8s clusters we observed following problem:
During eviction of the Worker Pod the pre-stop-hook.sh was triggered as expected.
With `fly -t infra workers` we could verify, that the worker state changed to "retiring".
But suddenly, the state changed back to `running`, for whatever reason.
Thus, the worker, even if it was in pod state `terminating` accepted new incoming concourse jobs.
And the worker was running until the pod.spec.terminationGracePeriodSeconds were reached.
*  With this PR, the pre-stop-hook easily sends the shutdownSignal again and again, assuring that the state remain `retiring`.
> This …
=> resend shutdownSignal to keep the state:retiring

README.md, values.yaml
The `concourse-chart/templates/web-deployment.yaml` file is looking for `Values.concourse.web.auth.userIDFieldPerConnector` but the parameter is in `concourse.web.auth.mainTeam.userIDFieldPerConnector`, according to the documentation.
* Change the parameter `userIDFieldPerConnector` to the correct place, which is `concourse.web.auth.userIDFieldPerConnector` instead of `concourse.web.auth.mainTeam.userIDFieldPerConnector` (or the opposite, if that's what is decided. But in that case it shouldn't go to the `master` branch).
- `dev` is for changes related to the next release of Concourse (aka unpublished code on `master` in …
=> fix: Change the "userIDFieldPerConnector" parameter's place

templates/_helpers.tpl, templates/worker-deployment.yaml, templates/worker-horizontal-pod-autoscaler.yaml, templates/worker-policy.yaml, templates/worker-statefulset.yaml
> Deprecated: use KubeVersion.Version
https://github.com/helm/helm/blob/82195652495d757d87c1a01f640973f20ca141b0/pkg/chartutil/capabilities.go#L82-L83
No, I was just confused by the deprecated references while reading the chart
Just to remove a use of deprecated helm-builtin
* `s/.Capabilities.KubeVersion.GitVersion/.Capabilities.KubeVersion.Version/`
=> Replace deprecated `.Capabilities.KubeVersion.GitVersion` references

templates/_helpers.tpl
worker.*.maxContainers documentation states it's 250 by default, and 0 is unlimited. However, setting it to 0 makes the template skip the env var, thus taking its default value.
Take into account that they can be to set 0.
=> Allow worker.*.maxContainers to be 0

templates/worker-deployment.yaml, values.yaml
Fixes #255
It seems the root container volume is read-only, so we can't write whatever we want to it anymore. Resolved by copying what we do in the StatefulSet and creating an emptyDir volume for the work dir. If someone is already using the workaround from #255, this change won't break anything for them, it'll skip creating the emptyDir.
=> Create emptyDir for worker when using kind Deployment

templates/worker-policy.yaml
Hello 👋 
The PodDisruptionBudget match labels are not specific enough. This does not present any issue with concourse itself but with some external tooling it is causing us issues. Additionally I think it is generally a good idea to match the match labels of the statefulset (in this case) so we don't accidentally start managing other similarly labeled pods
Good practices
It would help me out haha
one line to match the match labels of the worker statefulset - https://github.com/concourse/concourse-chart/blob/410e3983eae64d6e36b9f49f6db896584a46fc5d/templates/worker-statefulset.yaml#L18-L20
- `dev` is for changes related to the next release of …
=> Pdb match labels

README.md, templates/worker-statefulset.yaml, values.yaml
Hello again 👋 
This PR adds in the ability to use the persistentVolumeClaimRetentionPolicy feature of statefulsets enabled by default in kubernetes 1.32.
Ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention
With the HPA autoscaling feature this is a nice quality of life to allow developers to choose how they want their PVs to be reclaimed. 
persistentVolumeClaimRetentionPolicy feature for worker statefulset and supporting documentation …
=> Worker volume retention policy
